name: DEPLOY
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node modules
        run: npm install
      - name: create .env
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "NOTION_API_TOKEN=${{ secrets.NOTION_API_TOKEN }}" >> .env
          echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude-from="rsync-exclude-list.txt"
          path: ./
          remote_path: /home/ubuntu/apps/wagumi-sbt
          remote_host: 54.92.49.172
          remote_user: ubuntu
          remote_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
